<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FeatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // seed feats
        DB::table('feats')->insert([
            [1, 'Dodge!', '', 0],
            [2, 'Die Hard', '', 0],
            [3, 'Flash of Insight', '', 0],
            [4, 'Total Focus', '', 0],
            [5, 'Last Heroic Act', '', 0],
            [6, 'All Guns Blazing', '', 0],
            [7, 'A Very Distinctive...', '', 0],
            [8, 'Bodyguard', '', 0],
            [9, 'Botch Job', '', 0],
            [10, 'Cat-like Reflexes', '', 0],
            [11, 'Codebreaker', '', 0],
            [12, 'Cauterise', '', 0],
            [13, 'Drug Resistance', '', 0],
            [14, 'Escape Artist', '', 0],
            [15, 'Firm Grip', '', 0],
            [16, 'Fly It Like You Stole It', '', 0],
            [17, 'Get Back In The Fight', '', 0],
            [18, 'Hunker Down', '', 0],
            [19, 'Explosives Insight', '', 0],
            [20, 'Electrical Insight', '', 0],
            [21, 'Computing Insight', '', 0],
            [22, 'Communications Insight', '', 0],
            [23, 'Mechanical Insight', '', 0],
            [24, 'Larceny Insight', '', 0],
            [25, 'Medical Insight', '', 0],
            [26, 'Interrogator', '', 0],
            [27, 'Killing Blow', '', 0],
            [28, 'Emergency Measures', '', 1],
            [29, 'Marksman', '', 0],
            [30, 'Natural Resistance', '', 0],
            [31, 'Negotiator', '', 0],
            [32, 'Numb3rs', '', 0],
            [33, 'Old College Professor', '', 0],
            [34, 'On Your Feet Soldier', '', 0],
            [35, 'Polyglot', '', 0],
            [36, 'Technical Mentor', '', 0],
            [37, 'Tick Tock Motherfucker', '', 0],
            [38, 'Tomb Raider', '', 0],
            [39, 'Torture Resistance', '', 0],
            [40, 'Tracker', '', 0],
            [41, 'We Have A Job To Do', '', 0],
            [42, 'Cryptographic Insight', '', 0],
        ]);
        // seed background feats
        DB::table('background_feat')->insert([
            [1, 1],
            [1, 2],
            [1, 3],
            [1, 4],
            [1, 5],
            [2, 1],
            [2, 2],
            [2, 3],
            [2, 4],
            [2, 5],
            [3, 1],
            [3, 2],
            [3, 3],
            [3, 4],
            [3, 5],
        ]);
        // seed skill feats
        DB::table('feat_skill')->insert([
            [1, 9],
            [2, 11],
            [2, 42],
            [3, 9],
            [3, 20],
            [4, 9],
            [4, 19],
            [5, 14],
            [5, 24],
            [6, 9],
            [6, 23],
            [7, 17],
            [7, 25],
            [8, 9],
            [8, 22],
            [9, 38],
            [11, 3],
            [12, 13],
            [12, 30],
            [14, 35],
            [15, 37],
            [16, 28],
            [21, 32],
            [22, 17],
            [22, 37],
            [24, 10],
            [24, 34],
            [27, 7],
            [27, 8],
            [28, 33],
            [29, 40],
            [30, 3],
            [32, 7],
            [33, 26],
            [35, 41],
            [36, 28],
            [38, 31],
            [42, 3],
            [43, 13],
            [43, 39],
            [44, 16],
            [60, 30],
            [69, 40],
            [71, 12],
            [73, 27],
            [73, 29],
            [75, 18],
            [76, 6],
            [78, 10],
            [78, 27],
            [81, 10],
            [82, 15],
            [82, 27],
            [87, 28],
            [88, 36],
        ]);
    }
}
