<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // seed skill categories
        DB::table('skill_categories')->insert([
            [
                'id' => 1,
                'name' => 'Technical',
                'cost' => 12,
                'scaling' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Science &amp; Social',
                'cost' => 9,
                'scaling' => 1,
            ],
            [
                'id' => 3,
                'name' => 'Complex',
                'cost' => 6,
                'scaling' => 0,
            ],
            [
                'id' => 4,
                'name' => 'Basic',
                'cost' => 3,
                'scaling' => 0,
            ],
            [
                'id' => 5,
                'name' => 'Combat',
                'cost' => -1,
                'scaling' => 0,
            ],
            [
                'id' => 6,
                'name' => 'Alien',
                'cost' => -1,
                'scaling' => 0,
            ],
        ]);

        // seed skills
        DB::table('skills')->insert([
            [
                'id' => 1,
                'name' => 'Computing',
                'skill_category_id' => 1,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 2,
                'name' => 'Cryptography',
                'skill_category_id' => 1,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 3,
                'name' => 'Electrical Engineering',
                'skill_category_id' => 1,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 4,
                'name' => 'Explosives Training',
                'skill_category_id' => 1,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 5,
                'name' => 'Larceny',
                'skill_category_id' => 1,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 6,
                'name' => 'Mechanical Engineering',
                'skill_category_id' => 1,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 7,
                'name' => 'Paramedic',
                'skill_category_id' => 1,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 8,
                'name' => 'Signals Intelligence (SIGINT)',
                'skill_category_id' => 1,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 9,
                'name' => 'Archeo-Anthropology',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 2,
                'specialty_type_id' => 1,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 10,
                'name' => 'Additional Archeo-Anthrology Speciality',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 1,
                'specialty_type_id' => 1,
                'repeatable' => 1,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 11,
                'name' => 'Astrophysics',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 12,
                'name' => 'Botany',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 13,
                'name' => 'Genetics & Evolutionary Biology',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 14,
                'name' => 'Linguistics',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 15,
                'name' => 'Material Science',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 16,
                'name' => 'Medical Doctor',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 17,
                'name' => 'Pathology',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 18,
                'name' => 'Physiology',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 19,
                'name' => 'Psychology',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 20,
                'name' => 'Psychotherapy',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 21,
                'name' => 'Pure Mathematics',
                'skill_category_id' => 2,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 22,
                'name' => 'Armorer',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 23,
                'name' => 'Astronaut',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 24,
                'name' => 'CasEvac Specialist',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 27,
                'name' => 'Close Protection',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 28,
                'name' => 'Dreaming Spires',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 29,
                'name' => 'Forensic Science',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 30,
                'name' => 'History and Philosophy',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 31,
                'name' => 'Hypnosis',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 32,
                'name' => 'Insider Information',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 33,
                'name' => 'Interrogation/Investigation',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 34,
                'name' => 'Law',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 35,
                'name' => 'Leadership',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 36,
                'name' => 'Medical Specialism',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 1,
                'specialty_type_id' => 2,
                'repeatable' => 20,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 37,
                'name' => 'Micro-Expressions',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 38,
                'name' => 'Negotiation',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 39,
                'name' => 'Piloting',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 40,
                'name' => 'Politics and Bureaucracy',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 41,
                'name' => 'Quantum Physics',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 42,
                'name' => 'Religion and Occult',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 43,
                'name' => 'SERE Training',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 44,
                'name' => 'Test Pilot',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 45,
                'name' => 'Leadership Extra Person',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 20,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 46,
                'name' => 'Basic Biology',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 47,
                'name' => 'Basic Botany',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 48,
                'name' => 'Basic Chemistry',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 49,
                'name' => 'Basic Computers',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 50,
                'name' => 'Basic Engineering',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 51,
                'name' => 'Basic Explosives Training',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 52,
                'name' => 'Basic Geology',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 53,
                'name' => 'Basic Language',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 1,
                'specialty_type_id' => 3,
                'repeatable' => 10,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 54,
                'name' => 'Basic Larceny',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 55,
                'name' => 'Basic Mathematics',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 56,
                'name' => 'Basic Physics',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 57,
                'name' => 'Basic Psychology',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 60,
                'name' => 'Endurance Training',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 1,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 5,
                'body' => 1,
                'vigor' => 0,
            ],
            [
                'id' => 61,
                'name' => 'Expert Knowledge: Computing',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 6,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 62,
                'name' => 'Expert Knowledge: Cryptography',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 6,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 63,
                'name' => 'Expert Knowledge: Electrical Engineering',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 6,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 64,
                'name' => 'Expert Knowledge: Explosives Training',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 6,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 65,
                'name' => 'Expert Knowledge: Larceny',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 6,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 66,
                'name' => 'Expert Knowledge: Mechanical Engineering',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 6,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 67,
                'name' => 'Expert Knowledge: Paramedic',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 6,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 68,
                'name' => 'Expert Knowledge: Signals Intelligence',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 6,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 69,
                'name' => 'Fish and Game',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 70,
                'name' => 'Heroic Vigor',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 5,
                'body' => 0,
                'vigor' => 1,
            ],
            [
                'id' => 71,
                'name' => 'Medic',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 72,
                'name' => 'Mythology',
                'skill_category_id' => 4,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 1,
                'specialty_type_id' => 4,
                'repeatable' => 10,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 73,
                'name' => 'Accuracy Training',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 12,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 74,
                'name' => 'Boxing',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 3,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 75,
                'name' => 'Breacher',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 3,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 76,
                'name' => 'Gunnery Training',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 6,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 77,
                'name' => 'Heavy Weapons',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 6,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 78,
                'name' => 'Martial Arts',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 12,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 79,
                'name' => 'Melee',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 3,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 80,
                'name' => 'Pistols',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 3,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 81,
                'name' => 'Point Man',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 3,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 82,
                'name' => 'Primitive Weaponry',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 9,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 83,
                'name' => 'Tactical Training',
                'skill_category_id' => 5,
                'description' => '',
                'upkeep' => 0,
                'cost' => 6,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 86,
                'name' => 'Physiology (B)',
                'skill_category_id' => 2,
                'description' => 'Discounted variant',
                'upkeep' => 0,
                'cost' => 3,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 87,
                'name' => 'Medical Doctor (B)',
                'skill_category_id' => 2,
                'description' => 'Discounted variant',
                'upkeep' => 0,
                'cost' => 3,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
            [
                'id' => 88,
                'name' => 'Subject Matter Expert',
                'skill_category_id' => 3,
                'description' => '',
                'upkeep' => 0,
                'cost' => 0,
                'specialties' => 0,
                'specialty_type_id' => NULL,
                'repeatable' => 0,
                'body' => 0,
                'vigor' => 0,
            ],
        ]);

        // seed skill specialties
        DB::table('skill_specialty')->insert([
            [
                'id' => 3,
                'name' => 'Celtic',
                'specialty_type_id' => 1,
            ],
            [
                'id' => 1,
                'name' => 'Egyptian',
                'specialty_type_id' => 1,
            ],
            [
                'id' => 7,
                'name' => 'Far East',
                'specialty_type_id' => 1,
            ],
            [
                'id' => 9,
                'name' => 'Germanic',
                'specialty_type_id' => 1,
            ],
            [
                'id' => 4,
                'name' => 'Greco-Roman',
                'specialty_type_id' => 1,
            ],
            [
                'id' => 8,
                'name' => 'Indo-Aryan',
                'specialty_type_id' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Mesoamerican',
                'specialty_type_id' => 1,
            ],
            [
                'id' => 6,
                'name' => 'Middle Eastern',
                'specialty_type_id' => 1,
            ],
            [
                'id' => 5,
                'name' => 'Native American',
                'specialty_type_id' => 1,
            ],
            [
                'id' => 10,
                'name' => 'Cardiothoracic',
                'specialty_type_id' => 2,
            ],
            [
                'id' => 11,
                'name' => 'Haematology',
                'specialty_type_id' => 2,
            ],
            [
                'id' => 12,
                'name' => 'Infectious Diseases',
                'specialty_type_id' => 2,
            ],
            [
                'id' => 15,
                'name' => 'Neurosurgery',
                'specialty_type_id' => 2,
            ],
            [
                'id' => 13,
                'name' => 'Oncology',
                'specialty_type_id' => 2,
            ],
            [
                'id' => 14,
                'name' => 'Plastic Surgery',
                'specialty_type_id' => 2,
            ],
            [
                'id' => 21,
                'name' => 'Arabic',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 28,
                'name' => 'Chinese (Cantonese)',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 27,
                'name' => 'Chinese (Mandarin)',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 16,
                'name' => 'French',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 32,
                'name' => 'Gaelic',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 17,
                'name' => 'German',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 22,
                'name' => 'Greek',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 20,
                'name' => 'Hebrew',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 26,
                'name' => 'Italian',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 30,
                'name' => 'Japanese',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 29,
                'name' => 'Korean',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 19,
                'name' => 'Latin',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 24,
                'name' => 'Norwegian',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 34,
                'name' => 'Polish',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 33,
                'name' => 'Portuguese',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 23,
                'name' => 'Russian',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 18,
                'name' => 'Spanish',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 31,
                'name' => 'Swahili',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 25,
                'name' => 'Swedish',
                'specialty_type_id' => 3,
            ],
            [
                'id' => 38,
                'name' => 'Aztec/Mayan',
                'specialty_type_id' => 4,
            ],
            [
                'id' => 40,
                'name' => 'Buddhism',
                'specialty_type_id' => 4,
            ],
            [
                'id' => 39,
                'name' => 'Hinduism',
                'specialty_type_id' => 4,
            ],
            [
                'id' => 35,
                'name' => 'Judeo-Christian',
                'specialty_type_id' => 4,
            ],
            [
                'id' => 37,
                'name' => 'Native American',
                'specialty_type_id' => 4,
            ],
            [
                'id' => 36,
                'name' => 'Norse',
                'specialty_type_id' => 4,
            ],
        ]);

        // seed skill prereqs
        DB::table('skill_prereqs')->insert([
            [
                'skill_id' => 16,
                'prereq_id' => 7,
                'always_required' => 0,
            ],
            [
                'skill_id' => 31,
                'prereq_id' => 19,
                'always_required' => 0,
            ],
            [
                'skill_id' => 31,
                'prereq_id' => 20,
                'always_required' => 0,
            ],
            [
                'skill_id' => 36,
                'prereq_id' => 7,
                'always_required' => 0,
            ],
            [
                'skill_id' => 37,
                'prereq_id' => 19,
                'always_required' => 0,
            ],
            [
                'skill_id' => 37,
                'prereq_id' => 20,
                'always_required' => 0,
            ],
            [
                'skill_id' => 41,
                'prereq_id' => 15,
                'always_required' => 0,
            ],
            [
                'skill_id' => 44,
                'prereq_id' => 39,
                'always_required' => 0,
            ],
            [
                'skill_id' => 45,
                'prereq_id' => 35,
                'always_required' => 0,
            ],
            [
                'skill_id' => 73,
                'prereq_id' => 83,
                'always_required' => 0,
            ],
            [
                'skill_id' => 75,
                'prereq_id' => 81,
                'always_required' => 0,
            ],
            [
                'skill_id' => 77,
                'prereq_id' => 83,
                'always_required' => 0,
            ],
            [
                'skill_id' => 82,
                'prereq_id' => 79,
                'always_required' => 0,
            ],
            [
                'skill_id' => 83,
                'prereq_id' => 80,
                'always_required' => 0,
            ],
            [
                'skill_id' => 86,
                'prereq_id' => 16,
                'always_required' => 0,
            ],
            [
                'skill_id' => 87,
                'prereq_id' => 18,
                'always_required' => 0,
            ],
        ]);

        // seed skill lockouts
        DB::table('skill_lockouts')->insert([
            [
                'skill_id' => 16,
                'lockout_id' => 18,
            ],
            [
                'skill_id' => 16,
                'lockout_id' => 87,
            ],
            [
                'skill_id' => 18,
                'lockout_id' => 16,
            ],
            [
                'skill_id' => 18,
                'lockout_id' => 86,
            ],
        ]);

        // seed skill discounts
        DB::table('skill_discounts')->insert([
            [
                'discounting_skill' => 46,
                'discounted_skill' => 13,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 46,
                'discounted_skill' => 17,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 46,
                'discounted_skill' => 18,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 47,
                'discounted_skill' => 12,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 48,
                'discounted_skill' => 15,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 49,
                'discounted_skill' => 1,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 49,
                'discounted_skill' => 8,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 50,
                'discounted_skill' => 3,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 50,
                'discounted_skill' => 6,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 51,
                'discounted_skill' => 4,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 52,
                'discounted_skill' => 9,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 53,
                'discounted_skill' => 14,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 54,
                'discounted_skill' => 5,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 55,
                'discounted_skill' => 2,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 55,
                'discounted_skill' => 21,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 56,
                'discounted_skill' => 15,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 56,
                'discounted_skill' => 41,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 57,
                'discounted_skill' => 19,
                'discount' => 3,
            ],
            [
                'discounting_skill' => 72,
                'discounted_skill' => 42,
                'discount' => 3,
            ],
        ]);

        // seed skill cards
        DB::table('card_type_skill')->insert([
            [
                'skill_id' => 1,
                'card_type_id' => 1,
                'number' => 6,
                'total' => 1,
            ],
            [
                'skill_id' => 2,
                'card_type_id' => 2,
                'number' => 6,
                'total' => 1,
            ],
            [
                'skill_id' => 3,
                'card_type_id' => 3,
                'number' => 6,
                'total' => 1,
            ],
            [
                'skill_id' => 4,
                'card_type_id' => 4,
                'number' => 6,
                'total' => 1,
            ],
            [
                'skill_id' => 5,
                'card_type_id' => 5,
                'number' => 6,
                'total' => 1,
            ],
            [
                'skill_id' => 6,
                'card_type_id' => 6,
                'number' => 6,
                'total' => 1,
            ],
            [
                'skill_id' => 7,
                'card_type_id' => 7,
                'number' => 6,
                'total' => 1,
            ],
            [
                'skill_id' => 8,
                'card_type_id' => 8,
                'number' => 6,
                'total' => 1,
            ],
            [
                'skill_id' => 49,
                'card_type_id' => 1,
                'number' => 1,
                'total' => 0,
            ],
            [
                'skill_id' => 49,
                'card_type_id' => 8,
                'number' => 1,
                'total' => 0,
            ],
            [
                'skill_id' => 50,
                'card_type_id' => 3,
                'number' => 1,
                'total' => 0,
            ],
            [
                'skill_id' => 50,
                'card_type_id' => 6,
                'number' => 1,
                'total' => 0,
            ],
            [
                'skill_id' => 51,
                'card_type_id' => 4,
                'number' => 1,
                'total' => 0,
            ],
            [
                'skill_id' => 54,
                'card_type_id' => 5,
                'number' => 1,
                'total' => 0,
            ],
            [
                'skill_id' => 55,
                'card_type_id' => 2,
                'number' => 1,
                'total' => 0,
            ],
            [
                'skill_id' => 61,
                'card_type_id' => 1,
                'number' => 1,
                'total' => 1,
            ],
            [
                'skill_id' => 62,
                'card_type_id' => 2,
                'number' => 1,
                'total' => 1,
            ],
            [
                'skill_id' => 63,
                'card_type_id' => 6,
                'number' => 1,
                'total' => 1,
            ],
            [
                'skill_id' => 64,
                'card_type_id' => 4,
                'number' => 1,
                'total' => 1,
            ],
            [
                'skill_id' => 65,
                'card_type_id' => 5,
                'number' => 1,
                'total' => 1,
            ],
            [
                'skill_id' => 67,
                'card_type_id' => 7,
                'number' => 1,
                'total' => 1,
            ],
            [
                'skill_id' => 68,
                'card_type_id' => 8,
                'number' => 1,
                'total' => 1,
            ],
        ]);

        // seed background skills
        DB::table('background_skill')->insert([
            [
                'background_id' => 1,
                'skill_id' => 71,
            ],
            [
                'background_id' => 1,
                'skill_id' => 74,
            ],
            [
                'background_id' => 1,
                'skill_id' => 79,
            ],
            [
                'background_id' => 1,
                'skill_id' => 80,
            ],
            [
                'background_id' => 1,
                'skill_id' => 83,
            ],
            [
                'background_id' => 2,
                'skill_id' => 32,
            ],
            [
                'background_id' => 2,
                'skill_id' => 71,
            ],
            [
                'background_id' => 2,
                'skill_id' => 74,
            ],
            [
                'background_id' => 2,
                'skill_id' => 79,
            ],
            [
                'background_id' => 2,
                'skill_id' => 80,
            ],
            [
                'background_id' => 3,
                'skill_id' => 28,
            ],
            [
                'background_id' => 3,
                'skill_id' => 71,
            ],
            [
                'background_id' => 3,
                'skill_id' => 74,
            ],
            [
                'background_id' => 3,
                'skill_id' => 79,
            ],
            [
                'background_id' => 3,
                'skill_id' => 80,
            ],
        ]);
    }
}
